/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarymanagementsystem;

/**
 *
 * @author Caloy
 */
public class Admin_Form extends javax.swing.JFrame {

    /**
     * Creates new form Admin_Form
     */
    public Admin_Form() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tabhome = new javax.swing.JPanel();
        home = new javax.swing.JLabel();
        tabuser = new javax.swing.JPanel();
        user = new javax.swing.JLabel();
        tabbooks = new javax.swing.JPanel();
        books = new javax.swing.JLabel();
        tabborrowreq = new javax.swing.JPanel();
        borrowreq = new javax.swing.JLabel();
        tabborrowed = new javax.swing.JPanel();
        borrowed = new javax.swing.JLabel();
        tabupdate = new javax.swing.JPanel();
        update = new javax.swing.JLabel();
        tablogout = new javax.swing.JPanel();
        logout = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1600, 900));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabhome.setBackground(new java.awt.Color(0,0,0,1));

        home.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        home.setText("HOME");

        javax.swing.GroupLayout tabhomeLayout = new javax.swing.GroupLayout(tabhome);
        tabhome.setLayout(tabhomeLayout);
        tabhomeLayout.setHorizontalGroup(
            tabhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabhomeLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(home)
                .addGap(25, 25, 25))
        );
        tabhomeLayout.setVerticalGroup(
            tabhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabhomeLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(home)
                .addGap(43, 43, 43))
        );

        jPanel1.add(tabhome, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 120, -1));

        tabuser.setBackground(new java.awt.Color(0,0,0,1));

        user.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        user.setText("USER");

        javax.swing.GroupLayout tabuserLayout = new javax.swing.GroupLayout(tabuser);
        tabuser.setLayout(tabuserLayout);
        tabuserLayout.setHorizontalGroup(
            tabuserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabuserLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(user)
                .addGap(33, 33, 33))
        );
        tabuserLayout.setVerticalGroup(
            tabuserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabuserLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(user)
                .addGap(43, 43, 43))
        );

        jPanel1.add(tabuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 120, -1));

        tabbooks.setBackground(new java.awt.Color(0,0,0,1));

        books.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        books.setText("BOOKS");

        javax.swing.GroupLayout tabbooksLayout = new javax.swing.GroupLayout(tabbooks);
        tabbooks.setLayout(tabbooksLayout);
        tabbooksLayout.setHorizontalGroup(
            tabbooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabbooksLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(books)
                .addGap(22, 22, 22))
        );
        tabbooksLayout.setVerticalGroup(
            tabbooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabbooksLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(books)
                .addGap(43, 43, 43))
        );

        jPanel1.add(tabbooks, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, 120, -1));

        tabborrowreq.setBackground(new java.awt.Color(0,0,0,1));

        borrowreq.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        borrowreq.setText("BORROW REQUEST");

        javax.swing.GroupLayout tabborrowreqLayout = new javax.swing.GroupLayout(tabborrowreq);
        tabborrowreq.setLayout(tabborrowreqLayout);
        tabborrowreqLayout.setHorizontalGroup(
            tabborrowreqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabborrowreqLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(borrowreq)
                .addGap(22, 22, 22))
        );
        tabborrowreqLayout.setVerticalGroup(
            tabborrowreqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabborrowreqLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(borrowreq)
                .addGap(43, 43, 43))
        );

        jPanel1.add(tabborrowreq, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 20, 230, -1));

        tabborrowed.setBackground(new java.awt.Color(0,0,0,1));

        borrowed.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        borrowed.setText("BORROWED BOOKS");

        javax.swing.GroupLayout tabborrowedLayout = new javax.swing.GroupLayout(tabborrowed);
        tabborrowed.setLayout(tabborrowedLayout);
        tabborrowedLayout.setHorizontalGroup(
            tabborrowedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabborrowedLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(borrowed)
                .addGap(22, 22, 22))
        );
        tabborrowedLayout.setVerticalGroup(
            tabborrowedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabborrowedLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(borrowed)
                .addGap(43, 43, 43))
        );

        jPanel1.add(tabborrowed, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 20, 240, -1));

        tabupdate.setBackground(new java.awt.Color(0,0,0,1));

        update.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        update.setText("UPDATE BOOKS");

        javax.swing.GroupLayout tabupdateLayout = new javax.swing.GroupLayout(tabupdate);
        tabupdate.setLayout(tabupdateLayout);
        tabupdateLayout.setHorizontalGroup(
            tabupdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabupdateLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(update)
                .addGap(18, 18, 18))
        );
        tabupdateLayout.setVerticalGroup(
            tabupdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabupdateLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(update)
                .addGap(43, 43, 43))
        );

        jPanel1.add(tabupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 20, 210, -1));

        tablogout.setBackground(new java.awt.Color(0,0,0,1));

        logout.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        logout.setText("Logout");

        javax.swing.GroupLayout tablogoutLayout = new javax.swing.GroupLayout(tablogout);
        tablogout.setLayout(tablogoutLayout);
        tablogoutLayout.setHorizontalGroup(
            tablogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tablogoutLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(logout)
                .addGap(22, 22, 22))
        );
        tablogoutLayout.setVerticalGroup(
            tablogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tablogoutLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(logout)
                .addGap(43, 43, 43))
        );

        jPanel1.add(tablogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1440, 20, 120, -1));

        jLabel1.setBackground(new java.awt.Color(0,0,0,1));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Caloy\\Documents\\Netbeans images\\menu list cover.jpg")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setBackground(java.awt.SystemColor.controlHighlight);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1600, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel books;
    private javax.swing.JLabel borrowed;
    private javax.swing.JLabel borrowreq;
    private javax.swing.JLabel home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel logout;
    private javax.swing.JPanel tabbooks;
    private javax.swing.JPanel tabborrowed;
    private javax.swing.JPanel tabborrowreq;
    private javax.swing.JPanel tabhome;
    private javax.swing.JPanel tablogout;
    private javax.swing.JPanel tabupdate;
    private javax.swing.JPanel tabuser;
    private javax.swing.JLabel update;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
