/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarymanagementsystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JFrame;
import javax.swing.ImageIcon;
import javax.swing.JTextField;
import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import javax.swing.*;
import java.awt.event.*;
import java.awt.*;

/**
 *
 * @author Caloy
 */
public class Login_Form extends javax.swing.JFrame {
    
    /**
     * Creates new form Login_Form
     */
    public Login_Form() {
        initComponents();
        this.setLocationRelativeTo(null);
        jPanel1.setFocusable(true);
           
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        login = new javax.swing.JLabel();
        clear = new javax.swing.JButton();
        show = new javax.swing.JLabel();
        hide = new javax.swing.JLabel();
        txtpassword = new javax.swing.JPasswordField();
        txtusername = new javax.swing.JTextField();
        signup = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        login.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        login.setText("LOGIN");
        login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginMouseClicked(evt);
            }
        });
        login.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                loginKeyPressed(evt);
            }
        });
        jPanel1.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 450, 310, 30));

        clear.setFont(new java.awt.Font("Century Gothic", 3, 12)); // NOI18N
        clear.setText("CLEAR");
        clear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel1.add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 410, 90, 20));

        show.setIcon(new javax.swing.ImageIcon("C:\\Users\\Caloy\\Downloads\\visibility (1).png")); // NOI18N
        show.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        show.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                showMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                showMouseReleased(evt);
            }
        });
        jPanel1.add(show, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 370, -1, -1));

        hide.setIcon(new javax.swing.ImageIcon("C:\\Users\\Caloy\\Downloads\\visibility (1).png")); // NOI18N
        hide.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(hide, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 370, -1, -1));

        txtpassword.setBackground(new java.awt.Color(0,0,0,1));
        txtpassword.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtpassword.setForeground(new java.awt.Color(102, 102, 102));
        txtpassword.setText("Type your password");
        txtpassword.setToolTipText("");
        txtpassword.setBorder(null);
        txtpassword.setEchoChar('\u0000');
        txtpassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtpasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtpasswordFocusLost(evt);
            }
        });
        txtpassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpasswordKeyPressed(evt);
            }
        });
        jPanel1.add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 360, 240, 40));

        txtusername.setBackground(new java.awt.Color(0,0,0,1));
        txtusername.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtusername.setForeground(new java.awt.Color(102, 102, 102));
        txtusername.setText("Type your username");
        txtusername.setToolTipText("");
        txtusername.setBorder(null);
        txtusername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtusernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtusernameFocusLost(evt);
            }
        });
        txtusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusernameActionPerformed(evt);
            }
        });
        jPanel1.add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, 270, 40));

        signup.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        signup.setForeground(new java.awt.Color(255, 153, 0));
        signup.setText("Sign Up");
        signup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signupMouseClicked(evt);
            }
        });
        jPanel1.add(signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 660, -1, 30));

        jLabel10.setBackground(new java.awt.Color(0,0,0,1));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymanagementsystem/LOGIN FORM.jpg"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // clear
        txtusername.setText("");
        txtpassword.setText("");
        txtusername.requestFocus();
    }//GEN-LAST:event_clearActionPerformed

    private void loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseClicked
        // TODO add your handling code here:
        Connection conn = LibraryManagementSystem.getConnection();
            conn = LibraryManagementSystem.getConnection();
            
        try{    
            
               //Accept username and password
                String username = txtusername.getText();
                String password = txtpassword.getText();
                //mysql query to run
                String sql = "select * from userdata where username  = '" + username + "'";
                Statement stm = conn.createStatement();
                ResultSet rs = stm.executeQuery(sql);
                
                
                String usertype = "";
                
                
                if (rs.next()){
                    if (password.equals(rs.getString("password"))&& username.equals(rs.getString("username"))){
                        username = (rs.getString("username"));
                        usertype = (rs.getString("usertype"));
                        
                        if (usertype.equals("admin")){
                            new Admin_Form().setVisible(true);
                            
                        }
                        else{
                            new Admin_Form().setVisible(true);
                            
                        }
                            dispose(); //close login page
                       
                    }
                    else{
                        JOptionPane.showMessageDialog(this, "Incorrect username or password");
                        txtusername.setText("");
                        txtpassword.setText("");
                    }
                }
                else{
                        JOptionPane.showMessageDialog(this, "Incorrect username or password");
                        txtusername.setText("");
                        txtpassword.setText("");
                    }
                
                //con.close();
            
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_loginMouseClicked

    private void txtusernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtusernameFocusGained
        
        if (txtusername.getText().equals("Type your username")){
            txtusername.setText("");
           
        }
        
        txtusername.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtusernameFocusGained

    private void txtusernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtusernameFocusLost
        
        if (txtusername.getText().equals("")){
            txtusername.setText("Type your username");
        }
        
        txtusername.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtusernameFocusLost

    private void txtusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusernameActionPerformed

    private void txtpasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpasswordFocusGained
        
        if(txtpassword.getText().equals("Type your password")){
            txtpassword.setText("");
            txtpassword.setEchoChar('*');
        }
        txtpassword.setForeground(Color.BLACK); 
    }//GEN-LAST:event_txtpasswordFocusGained

    private void txtpasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpasswordFocusLost
        
        if(txtpassword.getText().equals("")){
            txtpassword.setText("Type your password");
            txtpassword.setEchoChar('*');
        }                                     
        txtpassword.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtpasswordFocusLost

    private void showMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showMousePressed
        
        show.setVisible(true);
        hide.setVisible(false);
        txtpassword.setEchoChar((char)0);
    }//GEN-LAST:event_showMousePressed

    private void showMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showMouseReleased
        show.setVisible(true);
        hide.setVisible(false);
        txtpassword.setEchoChar('*');
        
    }//GEN-LAST:event_showMouseReleased

    private void txtpasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpasswordKeyPressed
        
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){Connection conn = LibraryManagementSystem.getConnection();
            conn = LibraryManagementSystem.getConnection();
            
        try{    
            
               //Accept username and password
                String username = txtusername.getText();
                String password = txtpassword.getText();
                //mysql query to run
                String sql = "select * from userdata where username  = '" + username + "'";
                Statement stm = conn.createStatement();
                ResultSet rs = stm.executeQuery(sql);
                
                
                String usertype = "";
                
                
                if (rs.next()){
                    if (password.equals(rs.getString("password"))&& username.equals(rs.getString("username"))){
                        username = (rs.getString("username"));
                        usertype = (rs.getString("usertype"));
                        
                        if (usertype.equals("admin")){
                            new LoginSuccessful().setVisible(true);
                            
                        }
                        else{
                            new LoginSuccessful().setVisible(true);
                            
                        }
                            dispose(); //close login page
                       
                    }
                    else{
                        JOptionPane.showMessageDialog(this, "Incorrect username or password");
                        txtusername.setText("");
                        txtpassword.setText("");
                    }
                }
                else{
                        JOptionPane.showMessageDialog(this, "Incorrect username or password");
                        txtusername.setText("");
                        txtpassword.setText("");
                    }
                
                //con.close();
            
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
          
      }
    }//GEN-LAST:event_txtpasswordKeyPressed

    private void loginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_loginKeyPressed
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            
        }     
    }//GEN-LAST:event_loginKeyPressed

    private void signupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupMouseClicked
        // TODO add your handling code here:
        new Signup_Form().setVisible(true);
        dispose();
    }//GEN-LAST:event_signupMouseClicked
        
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clear;
    private javax.swing.JLabel hide;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel login;
    private javax.swing.JLabel show;
    private javax.swing.JLabel signup;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
