/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarymanagementsystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JFrame;
import javax.swing.ImageIcon;
import javax.swing.JTextField;
import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import javax.swing.*;
import java.awt.event.*;
import java.awt.*;

/**
 *
 * @author Caloy
 */
public class Signup_Form extends javax.swing.JFrame {

    /**
     * Creates new form Signup_Form
     */
    public Signup_Form() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtusername = new javax.swing.JTextField();
        txtpassword = new javax.swing.JPasswordField();
        txtfname = new javax.swing.JTextField();
        txtlname = new javax.swing.JTextField();
        txtmi = new javax.swing.JTextField();
        txtaddress = new javax.swing.JTextField();
        txtcontact = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        cmbgender = new javax.swing.JComboBox<>();
        cmbusertype = new javax.swing.JComboBox<>();
        signup = new javax.swing.JLabel();
        loginhere = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtusername.setBackground(new java.awt.Color(0,0,0,1));
        txtusername.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtusername.setBorder(null);
        jPanel1.add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 180, 260, 30));

        txtpassword.setBackground(new java.awt.Color(0,0,0,1));
        txtpassword.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtpassword.setBorder(null);
        jPanel1.add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, 260, 30));

        txtfname.setBackground(new java.awt.Color(0,0,0,1));
        txtfname.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtfname.setBorder(null);
        jPanel1.add(txtfname, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 290, 80, 30));

        txtlname.setBackground(new java.awt.Color(0,0,0,1));
        txtlname.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtlname.setBorder(null);
        jPanel1.add(txtlname, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 290, 80, 30));

        txtmi.setBackground(new java.awt.Color(0,0,0,1));
        txtmi.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtmi.setBorder(null);
        jPanel1.add(txtmi, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 290, 60, 30));

        txtaddress.setBackground(new java.awt.Color(0,0,0,1));
        txtaddress.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtaddress.setBorder(null);
        jPanel1.add(txtaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 400, 260, 30));

        txtcontact.setBackground(new java.awt.Color(0,0,0,1));
        txtcontact.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtcontact.setBorder(null);
        jPanel1.add(txtcontact, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 460, 260, 20));

        txtemail.setBackground(new java.awt.Color(0,0,0,1));
        txtemail.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtemail.setBorder(null);
        jPanel1.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 520, 260, 20));

        cmbgender.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        cmbgender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        cmbgender.setBorder(null);
        cmbgender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbgenderActionPerformed(evt);
            }
        });
        jPanel1.add(cmbgender, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 340, 110, 40));

        cmbusertype.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        cmbusertype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "user", "admin" }));
        jPanel1.add(cmbusertype, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 550, 110, 50));

        signup.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        signup.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signup.setText("SIGNUP");
        signup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signupMouseClicked(evt);
            }
        });
        jPanel1.add(signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 620, 300, 40));

        loginhere.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        loginhere.setText("Login Here");
        loginhere.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginhere.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginhereMouseClicked(evt);
            }
        });
        jPanel1.add(loginhere, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 700, -1, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Caloy\\Documents\\Netbeans images\\REGISTER FORM.jpg")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginhereMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginhereMouseClicked
        
        new Login_Form().setVisible(true);
        dispose();
        
    }//GEN-LAST:event_loginhereMouseClicked

    private void cmbgenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbgenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbgenderActionPerformed

    private void signupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupMouseClicked
        
        Connection conn = LibraryManagementSystem.getConnection();
            conn = LibraryManagementSystem.getConnection();
        
            String username = txtusername.getText();
            String password = txtpassword.getText();
            String fname = txtfname.getText();
            String lname = txtlname.getText();
            String mi = txtmi.getText();
            String address = txtaddress.getText();
            String contact = txtcontact.getText();
            String email = txtemail.getText();
            String gender = String.valueOf(cmbgender.getSelectedItem());
            String usertype = String.valueOf(cmbusertype.getSelectedItem());
            
            String sql = "";
            
        
        
        if (username.equals("") || password.equals("") || fname.equals("") || lname.equals("") || mi.equals("") || address.equals("") || contact.equals("") || email.equals("")){
            JOptionPane.showMessageDialog(this, "Please fill up all fields");
        }
        else{
            try{
                sql = "select * from userdata where username = '" + username + "'";
                Statement stm = conn.createStatement();
                ResultSet rs = stm.executeQuery(sql);
                
                if (rs.next()){
                    JOptionPane.showMessageDialog(this, "Username is already exist");
                }
                else{
                    sql = "insert into userdata(username, password, F_name, L_name, M_name, Gender, Address, Contact_Num, Email, usertype, status) values ('" 
                            + username + "', '" + password + "', '" + fname + "', '" + lname + "', '" + mi + "', '" 
                            + gender + "', '" + address + "', '" + contact + "', '" + email + "', '" + usertype + "', 'Activated')";

                    stm.execute(sql);

                    JOptionPane.showMessageDialog(this, "Registered Successfully!");
                    
                    stm.close();
                    if (usertype.equals("user")){
                        //login.show();
                        new LoginSuccessful().setVisible(true);
                    }
                    else{
                        //admin.show();
                        new LoginSuccessful().setVisible(true);
                    }
                    
                    dispose();

                }

            }catch(Exception e){
                System.out.println(e.getMessage());
            }
        }

    }//GEN-LAST:event_signupMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbgender;
    private javax.swing.JComboBox<String> cmbusertype;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel loginhere;
    private javax.swing.JLabel signup;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JTextField txtcontact;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtfname;
    private javax.swing.JTextField txtlname;
    private javax.swing.JTextField txtmi;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
